name: widgetbook_generator
description: A package to automate setup and maintanance of the widgetbook package by using code generation.
version: 3.0.0-beta.10
homepage: https://www.widgetbook.io?utm_source=pub.dev&utm_medium=link&utm_campaign=widgetbook_generator
repository: https://github.com/widgetbook/widgetbook
issue_tracker: https://github.com/widgetbook/widgetbook/issues
documentation: https://docs.widgetbook.io/widgetbook-generator/overview

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  analyzer: ^5.10.0
  build: ^2.3.1
  collection: ^1.17.1
  freezed_annotation: ^2.2.0
  glob: ^2.1.1
  json_annotation: ^4.8.0
  meta: ^1.9.1
  source_gen: ^1.2.7
  widgetbook_annotation: ^3.0.0-beta.6
  widgetbook_models: ^3.0.0-beta.3
dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  test: ^1.24.1