on: 
  pull_request:
    paths:
      - "packages/widgetbook_git/**"
      - ".github/workflows/widgetbook-git.yaml"
  push:
    branches:
      - main
name: widgetbook_git
jobs:
  test:
    name: test
    defaults:
      run:
        working-directory: packages/widgetbook_git
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
    - uses: dart-lang/setup-dart@v1.3

    - name: Dart version
      run: dart --version

    - name: Set a git dummy user
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"      

    - name: Run Tests
      run: |
        dart pub global activate coverage 1.2.0
        dart test --coverage=coverage && dart pub global run coverage:format_coverage --lcov --in=coverage --out=coverage/lcov.info --packages=.dart_tool/package_config.json --report-on=lib
   
    - name: Check Code Coverage
      uses: VeryGoodOpenSource/very_good_coverage@v2.2.0
      with:
        path: packages/widgetbook_git/coverage/lcov.info    
        min_coverage: 70

  code-quality:
    defaults:
      run:
        working-directory: packages/widgetbook_git
    name: code quality
    runs-on: ubuntu-latest 
    steps:

    - uses: actions/checkout@v3
    - uses: dart-lang/setup-dart@v1.3

    - name: Get packages 
      run: dart pub get

    - name: Run analyze
      run: dart analyze